export const cryptoCoins = {
  BTC: {
    title: 'Bitcoin',
    img: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    ticker: 'BTC',
    value: '38700',
    percentChange: '3.2',
  },
  ETH: {
    title: 'Ethereum',
    img: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    ticker: 'ETH',
    value: '2500',
    percentChange: '-1.8',
  },
  BNB: {
    title: 'Binance Coin',
    img: 'https://cryptologos.cc/logos/binance-coin-bnb-logo.png',
    ticker: 'BNB',
    value: '410',
    percentChange: '2.0',
  },
  ADA: {
    title: 'Cardano',
    img: 'https://cryptologos.cc/logos/cardano-ada-logo.png',
    ticker: 'ADA',
    value: '0.95',
    percentChange: '-0.5',
  },
  SOL: {
    title: 'Solana',
    img: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    ticker: 'SOL',
    value: '101',
    percentChange: '4.5',
  },
  XRP: {
    title: 'XRP',
    img: 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
    ticker: 'XRP',
    value: '0.78',
    percentChange: '-1.2',
  },
  DOT: {
    title: 'Polkadot',
    img: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png',
    ticker: 'DOT',
    value: '18',
    percentChange: '3.0',
  },
  DOGE: {
    title: 'Dogecoin',
    img: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
    ticker: 'DOGE',
    value: '0.12',
    percentChange: '-2.3',
  },
  SHIB: {
    title: 'Shiba Inu',
    img: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png',
    ticker: 'SHIB',
    value: '0.000022',
    percentChange: '1.0',
  },
  LTC: {
    title: 'Litecoin',
    img: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
    ticker: 'LTC',
    value: '106',
    percentChange: '1.5',
  },
};
